# config.yaml

port: 3333
chain_rpc: "http://ch01.darkindex.net:8333/rpc"

# If true, skip mining.authorize checks and accept all miners
allow_anonymous: true

difficulty: 1000
work_interval: 5

# Add this line (your real threat feed URL)
threat_endpoint: "http://ch01.darkindex.net:8333/block"
